### ISSUE TITLE
Web Responsiveness

### ISSUE THREAD

**Issue by ravimahfunda** [RelieveID/relieve_landing_page#4]
- [x] Navbar Brand overlap dengan Navigation
- [x] Viewport Responsiveness, seperti gambar diatas
![image](https://user-images.githubusercontent.com/23191531/58385391-ea014400-8019-11e9-9afb-aa6e3d17acd0.png)

- [x] Image Positioning
![image](https://user-images.githubusercontent.com/23191531/58385408-32206680-801a-11e9-9e7b-afa5069e85c1.png)

- [x] Image Scaling
![image](https://user-images.githubusercontent.com/23191531/58385423-685de600-801a-11e9-94cf-be54cd861e57.png)

- [x] Button margin on CTA
![image](https://user-images.githubusercontent.com/23191531/58385428-83c8f100-801a-11e9-8dd8-e6457b769ce4.png)

- [x] Overlapping content on various screen sizes
![image](https://user-images.githubusercontent.com/23191531/58385445-c8548c80-801a-11e9-8730-773ddd34f073.png)

**Comment by alifgiant** [comment]
okay.. nanti di fix

further progress see #3

**Comment by alifgiant** [comment]
updated @ravimahfunda
